platform :ios, '11.0'

target 'VideoCamera' do
pod 'PonyDebugger', :git => 'https://github.com/huangjimmy/PonyDebugger.git', :configurations => ['Debug']
pod 'Reveal-SDK', '12', :configurations => ['Debug']
pod 'FileBrowser', '~> 1.0'
pod 'DeviceGuru', '~> 5.0'
pod 'SVProgressHUD'
end
